 services:
   node-hello:
     image: node-hello
     build: .
     environment:
       NODE_ENV: development
     ports:
       - 3002
       - 9229:9229
     command: node --inspect=0.0.0.0:9229 ./bin/www